# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
